name: build-toolchain-docker-image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build toolchain/estimators --file toolchain/estimators/Dockerfile --tag staging

    - name: Configure AWS Credential
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Push API to AWS
      run: |
        docker tag staging:latest public.ecr.aws/h0m6q0n8/estimators/staging:latest
        docker push public.ecr.aws/h0m6q0n8/estimators/staging:latest
